config/routes.rb
Rails.application.routes.draw do

  root 'photos#random'

  resources :photos, only: [:edit, :update] do
    get :random, on: :collection
    get :undo, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  path       :text             not null
#  tagged_at  :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  filename   :text
#
# Indexes
#
#  index_photos_on_path  (path) UNIQUE
#

class Photo < ActiveRecord::Base
  scope :random_order, -> { order("RANDOM()") }
  scope :tagged, -> (tag) { includes(:tags).where(tags: { name: tag }) }

  has_and_belongs_to_many :tags

  validates :path, presence: true
  validates :path, uniqueness: true

  before_create -> (){ self.filename = File.basename(self.path) }

  def asset_path
    "photo_library/#{filename}"
  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer
#
# Indexes
#
#  index_tags_on_name  (name) UNIQUE
#

class Tag < ActiveRecord::Base
  belongs_to :group, class_name: TagGroup, foreign_key: :group_id
  has_and_belongs_to_many :photos

  validates :name, presence: true
  validates :name, uniqueness: true

  def self.list
    self.all.map(&:name)
  end
end

app/models/tag_group.rb
# == Schema Information
#
# Table name: tag_groups
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tag_groups_on_name  (name) UNIQUE
#

class TagGroup < ActiveRecord::Base
  has_many :tags, foreign_key: :group_id
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def edit
    @photo = Photo.find(params[:id])
    tag_groups
  end

  def update
    @photo = Photo.find(params[:id])

    @photo.tag_ids = tag_ids_from_params
    @photo.tagged_at = (@photo.tag_ids.empty?) ? nil : DateTime.now

    flash.alert = "Error" unless @photo.save
    redirect_to root_path
  end

  def random
    @photo = Photo.where(tagged_at: nil).random_order.first
    tag_groups
    render :edit
  end

  def undo
    @photo = Photo.where.not(tagged_at: nil).order(:tagged_at).last
    @photo.update(tagged_at: nil)
    tag_groups
    render :edit
  end

  private

  def tag_ids_from_params
    params[:tag_ids].select {|k, v| v == "1"}.keys
  end

  def tag_groups
    @tag_groups = TagGroup.includes(:tags)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  body
    
    - flash.each do |key, value|
      .callout class=key data-closable=""
        = value
        button.close-button aria-label="Dismiss alert" data-close="" type="button" 
          span aria-hidden="true"  &times;
        
    .row
      == yield

app/views/photos/edit.html.slim
.main.column
  .photo-container
    - if @photo
      = image_tag @photo.asset_path, id: 'photo'

.sidebar.shrink.column
  - if @photo
    - completed, total = Photo.where.not(tagged_at: nil).count, Photo.count
    - percent = (completed.to_f / total.to_f * 100).round
    h6.text-right= "#{completed} / #{total} (#{percent}%)"
    h6= @photo.filename
    
    = simple_form_for @photo do |f|
      = simple_fields_for :tag_ids do |t|
        
        - @tag_groups.each do |group|
            .tag-group class=group.name
              - group.tags.each do |tag|
                = t.input tag.id, label: tag.name, as: :boolean, 
                  wrapper_html: { class: "button hollow" },
                  input_html: { checked: @photo.tag_ids.include?(tag.id) }
      
      = f.button :submit, "Tag Photo", class: "submit full-width"
      = link_to "Undo", undo_photos_path, class: "button secondary full-width"